version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: is-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: is-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    restart: always

  db:
    image: postgres:12
    container_name: sonar-db
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  sonarnet:

volumes:
  postgres_data:
