sonar.projectKey=ISPlayground
sonar.projectName=ISPlayground
sonar.projectVersion=1.0

sonar.sources=backend/app/core,frontend/src/pages

sonar.exclusions=**/tests/**, **/node_modules/**, **/*.css, **/*.html

sonar.coverage.exclusions=frontend/**/*

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
